
spring.application.name=demo



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/your_database}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:your_username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_password}

# JPA settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop} 
#CREATE-DROP/UPDATE/NONE/VALIDATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ---------------------------------------------------------------
# Logging
# ---------------------------------------------------------------
 
#debug level 
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
 
#log file
logging.file.name=logs/your_app.log
 
# logging settings size days ...
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
 
# Pattern: timestamp  level  thread  logger  — message
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n